import pubchempy as pcp

from rdkit import Chem
from rdkit.Chem import Fragments

import random as rd

my_seed = 32

rd.seed(my_seed)

def detector_de_grupos_funcionais(mol_name):
    compound = pcp.get_compounds(mol_name, 'name')

    mol = Chem.MolFromSmiles(compound[0].isomeric_smiles)

    grupos_funcionais = {
    "Ácidos carboxilicos alifáticos": {"Número": Fragments.fr_Al_COO(mol),
                                       "Massa Molecular": rd.uniform(0.5, 50),
                                       "Área de Superfície": rd.uniform(0.1, 5),
                                       "LogP": rd.random(),
                                       "Anéis Aromáticos": rd.randint(0,5),
                                       "Número de Rotâmeros": rd.randint(0,5),
                                       "Polaridade": rd.uniform(0, 300),
                                       "Raio Molecular": rd.randint(0,100)},
    "Hidroxilas alifáticas": {"Número": Fragments.fr_Al_OH(mol),
                              "Massa Molecular": rd.uniform(0.5, 50),
                              "Área de Superfície": rd.uniform(0.1, 5),
                              "LogP": rd.random(),
                              "Anéis Aromáticos": rd.randint(0,5),
                              "Número de Rotâmeros": rd.randint(0,5),
                              "Polaridade": rd.uniform(0, 300),
                              "Raio Molecular": rd.randint(0,100)},
    "Hidroxilas alifáticas excluindo tert-OH": Fragments.fr_Al_OH_noTert(mol),
    "Grupos funcionais N ligado à aromáticos": Fragments.fr_ArN(mol),
    "Ácidos carboxilicos aromáticos": Fragments.fr_Ar_COO(mol),
    "Nitrogênios aromáticos": Fragments.fr_Ar_N(mol),
    "Aminas aromáticas": Fragments.fr_Ar_NH(mol),
    "Hidroxilas aromáticas": Fragments.fr_Ar_OH(mol),
    "Ácidos carboxilicos": Fragments.fr_COO(mol),
    "Ácidos carboxílicos": Fragments.fr_COO2(mol),
    "Carbonilas O": Fragments.fr_C_O(mol),
    "Carbonilas O excluindo COOH": Fragments.fr_C_O_noCOO(mol),
    "Tiocarbonilas": Fragments.fr_C_S(mol),
    "C(OH)CCN-Ctert-alkyl ou C(OH)CCNcyclic": Fragments.fr_HOCCN(mol),
    "Iminas": Fragments.fr_Imine(mol),
    "Aminas": Fragments.fr_NH0(mol),
    "Aminas secundárias": Fragments.fr_NH1(mol),
    "Aminas primárias": Fragments.fr_NH2(mol),
    "Hidroxilaminas": Fragments.fr_N_O(mol),
    "XCCNR": Fragments.fr_Ndealkylation1(mol),
    "Aminas terc-alicíclicas": Fragments.fr_Ndealkylation2(mol),
    "Nitrogênios H-Pirrol": Fragments.fr_Nhpyrrole(mol),
    "Grupos tiol": Fragments.fr_SH(mol),
    "Aldeídos": Fragments.fr_aldehyde(mol),
    "Alquil carbamatos (sujeitos a hidrólise)": Fragments.fr_alkyl_carbamate(mol),
    "Haletos de alquila": Fragments.fr_alkyl_halide(mol),
    "Isotiocianatos": Fragments.fr_isothiocyan(mol),
    "Sítios de oxidação alílica excluindo dienona esteróide": Fragments.fr_allylic_oxid(mol),
    "Amidas": Fragments.fr_amide(mol),
    "Grupos de amidina": Fragments.fr_amidine(mol),
    "Anilinas": Fragments.fr_aniline(mol),
    "Sítios aril metil para hidroxilação": Fragments.fr_aryl_methyl(mol),
    "Azidas": Fragments.fr_azide(mol),
    "Grupos azo": Fragments.fr_azo(mol),
    "Grupos de barbitúricos": Fragments.fr_barbitur(mol),
    "Anéis de benzeno": Fragments.fr_benzene(mol),
    "Benzodiazepínicos sem anéis fundidos adicionais": Fragments.fr_benzodiazepine(mol),
    "Biciclicos": Fragments.fr_bicyclic(mol),
    "Grupos diazo": Fragments.fr_diazo(mol),
    "Diidropiridinas": Fragments.fr_dihydropyridine(mol),
    "Anéis de expóxido": Fragments.fr_epoxide(mol),
    "Ésters": Fragments.fr_ester(mol),
    "Éters": Fragments.fr_ether(mol),
    "Furano": Fragments.fr_furan(mol),
    "Grupos guanidina": Fragments.fr_guanido(mol),
    "Halogênios": Fragments.fr_halogen(mol),
    "Grupos de hidrazina": Fragments.fr_hdrzine(mol),
    "Grupos de hidrazona": Fragments.fr_hdrzone(mol),
    "Anéis de imidazol": Fragments.fr_imidazole(mol),
    "Grupos imide": Fragments.fr_imide(mol),
    "Isocianatos": Fragments.fr_isocyan(mol),
    "Tioéteres": Fragments.fr_sulfide(mol),
    "Cetonas": Fragments.fr_ketone(mol),
    "Cetonas excluindo diaril, a,b-insat. dienonas, heteroátomo em Calpha": Fragments.fr_ketone_Topliss(mol),
    "Beta lactâmicos": Fragments.fr_lactam(mol),
    "Ésteres cíclicos (lactonas)": Fragments.fr_lactone(mol),
    "Grupos metoxi -OCH3": Fragments.fr_methoxy(mol),
    "Anéis de morfolina": Fragments.fr_morpholine(mol),
    "Nitrilos": Fragments.fr_nitrile(mol),
    "Grupos nitro": Fragments.fr_nitro(mol),
    "Substituintes do anel nitro benzeno": Fragments.fr_nitro_arom(mol),
    "Substituintes do anel nitro benzeno não orto": Fragments.fr_nitro_arom_nonortho(mol),
    "Grupos nitroso excluindo NO2": Fragments.fr_nitroso(mol),
    "Anéis de oxazol": Fragments.fr_oxazole(mol),
    "Grupos oxima": Fragments.fr_oxime(mol),
    "Locais de para-hidroxilação": Fragments.fr_para_hydroxylation(mol),
    "Fenóis": Fragments.fr_phenol(mol),
    "OH fenólico excluindo substituintes Hbond intramoleculares orto": Fragments.fr_phenol_noOrthoHbond(mol),
    "Grupos de ácido fosfórico": Fragments.fr_phos_acid(mol),
    "Grupos éster fosfórico": Fragments.fr_phos_ester(mol),
    "Anéis de piperdina": Fragments.fr_piperdine(mol),
    "Anéis de piperzina": Fragments.fr_piperzine(mol),
    "Amidas primárias": Fragments.fr_priamide(mol),
    "Sulfonamidas primárias": Fragments.fr_prisulfonamd(mol),
    "Anéis de piridina": Fragments.fr_pyridine(mol),
    "Nitrogênios quaternários": Fragments.fr_quatN(mol),
    "Sulfonamidas": Fragments.fr_sulfonamd(mol),
    "Grupos sulfona": Fragments.fr_sulfone(mol),
    "Acetilenos terminais": Fragments.fr_term_acetylene(mol),
    "Anéis de tetrazol": Fragments.fr_tetrazole(mol),
    "Anéis tiazólicos": Fragments.fr_thiazole(mol),
    "Tiocianatos": Fragments.fr_thiocyan(mol),
    "Anéis de tiofeno": Fragments.fr_thiophene(mol),
    "Alcanos não ramificados de pelo menos 4 membros (exclui alcanos halogenados)": Fragments.fr_unbrch_alkane(mol),
    "Grupos de ureia": Fragments.fr_urea(mol)}

    return grupos_funcionais