import pubchempy as pcp

from rdkit import Chem
from rdkit.Chem import Fragments

import random as rd

my_seed = 32

rd.seed(my_seed)


def detector_de_grupos_funcionais(mol_name):
    compound = pcp.get_compounds(mol_name, "name")

    mol = Chem.MolFromSmiles(compound[0].isomeric_smiles)

    grupos_funcionais = {
        "Ácidos carboxilicos alifáticos": {
            "Número": Fragments.fr_Al_COO(mol),
            "Massa Molecular": rd.uniform(0.5, 50),
            "Área de Superfície": rd.uniform(0.1, 5),
            "LogP": rd.random(),
            "Anéis Aromáticos": rd.randint(0, 5),
            "Número de Rotâmeros": rd.randint(0, 5),
            "Polaridade": rd.uniform(0, 300),
            "Raio Molecular": rd.randint(0, 100),
        },
        "Hidroxilas alifáticas": {
            "Número": Fragments.fr_Al_OH(mol),
            "Massa Molecular": rd.uniform(0.5, 50),
            "Área de Superfície": rd.uniform(0.1, 5),
            "LogP": rd.random(),
            "Anéis Aromáticos": rd.randint(0, 5),
            "Número de Rotâmeros": rd.randint(0, 5),
            "Polaridade": rd.uniform(0, 300),
            "Raio Molecular": rd.randint(0, 100),
        },
        "Hidroxilas alifáticas excluindo tert-OH": Fragments.fr_Al_OH_noTert(mol),
        "Grupos funcionais N ligado à aromáticos": Fragments.fr_ArN(mol),
        "Ácidos carboxilicos aromáticos": Fragments.fr_Ar_COO(mol),
        "Nitrogênios aromáticos": Fragments.fr_Ar_N(mol),
        "Aminas aromáticas": Fragments.fr_Ar_NH(mol),
        "Hidroxilas aromáticas": Fragments.fr_Ar_OH(mol),
        "Ácidos carboxilicos": Fragments.fr_COO(mol),
        "Ácidos carboxílicos": Fragments.fr_COO2(mol),
        "Carbonilas O": Fragments.fr_C_O(mol),
        "Carbonilas O excluindo COOH": Fragments.fr_C_O_noCOO(mol),
        "Tiocarbonilas": Fragments.fr_C_S(mol),
        "C(OH)CCN-Ctert-alkyl ou C(OH)CCNcyclic": Fragments.fr_HOCCN(mol),
        "Iminas": Fragments.fr_Imine(mol),
        "Aminas": Fragments.fr_NH0(mol),
        "Aminas secundárias": Fragments.fr_NH1(mol),
        "Aminas primárias": Fragments.fr_NH2(mol),
        "Hidroxilaminas": Fragments.fr_N_O(mol),
        "XCCNR": Fragments.fr_Ndealkylation1(mol),
        "Aminas terc-alicíclicas": Fragments.fr_Ndealkylation2(mol),
        "Nitrogênios H-Pirrol": Fragments.fr_Nhpyrrole(mol),
        "Grupos tiol": Fragments.fr_SH(mol),
        "Aldeídos": Fragments.fr_aldehyde(mol),
        "Alquil carbamatos (sujeitos a hidrólise)": Fragments.fr_alkyl_carbamate(mol),
        "Haletos de alquila": Fragments.fr_alkyl_halide(mol),
        "Isotiocianatos": Fragments.fr_isothiocyan(mol),
        "Sítios de oxidação alílica excluindo dienona esteróide": Fragments.fr_allylic_oxid(
            mol
        ),
        "Amidas": Fragments.fr_amide(mol),
        "Grupos de amidina": Fragments.fr_amidine(mol),
        "Anilinas": Fragments.fr_aniline(mol),
        "Sítios aril metil para hidroxilação": Fragments.fr_aryl_methyl(mol),
        "Azidas": Fragments.fr_azide(mol),
        "Grupos azo": Fragments.fr_azo(mol),
        "Grupos de barbitúricos": Fragments.fr_barbitur(mol),
        "Anéis de benzeno": Fragments.fr_benzene(mol),
        "Benzodiazepínicos sem anéis fundidos adicionais": Fragments.fr_benzodiazepine(
            mol
        ),
        "Biciclicos": Fragments.fr_bicyclic(mol),
        "Grupos diazo": Fragments.fr_diazo(mol),
        "Diidropiridinas": Fragments.fr_dihydropyridine(mol),
        "Anéis de expóxido": Fragments.fr_epoxide(mol),
        "Ésters": Fragments.fr_ester(mol),
        "Éters": Fragments.fr_ether(mol),
        "Furano": Fragments.fr_furan(mol),
        "Grupos guanidina": Fragments.fr_guanido(mol),
        "Halogênios": Fragments.fr_halogen(mol),
        "Grupos de hidrazina": Fragments.fr_hdrzine(mol),
        "Grupos de hidrazona": Fragments.fr_hdrzone(mol),
        "Anéis de imidazol": Fragments.fr_imidazole(mol),
        "Grupos imide": Fragments.fr_imide(mol),
        "Isocianatos": Fragments.fr_isocyan(mol),
        "Tioéteres": Fragments.fr_sulfide(mol),
        "Cetonas": Fragments.fr_ketone(mol),
        "Cetonas excluindo diaril, a,b-insat. dienonas, heteroátomo em Calpha": Fragments.fr_ketone_Topliss(
            mol
        ),
        "Beta lactâmicos": Fragments.fr_lactam(mol),
        "Ésteres cíclicos (lactonas)": Fragments.fr_lactone(mol),
        "Grupos metoxi -OCH3": Fragments.fr_methoxy(mol),
        "Anéis de morfolina": Fragments.fr_morpholine(mol),
        "Nitrilos": Fragments.fr_nitrile(mol),
        "Grupos nitro": Fragments.fr_nitro(mol),
        "Substituintes do anel nitro benzeno": {
            "Número": Fragments.fr_nitro_arom(mol),
            "Massa Molecular": rd.uniform(0.5, 50),
            "Área de Superfície": rd.uniform(0.1, 5),
            "LogP": rd.random(),
            "Anéis Aromáticos": rd.randint(0, 5),
            "Número de Rotâmeros": rd.randint(0, 5),
            "Polaridade": rd.uniform(0, 300),
            "Raio Molecular": rd.randint(0, 100),
        },
        "Substituintes do anel nitro benzeno não orto": {
            "Número": Fragments.fr_nitro_arom_nonortho(mol),
            "Massa Molecular": rd.uniform(0.5, 50),
            "Área de Superfície": rd.uniform(0.1, 5),
            "LogP": rd.random(),
            "Anéis Aromáticos": rd.randint(0, 5),
            "Número de Rotâmeros": rd.randint(0, 5),
            "Polaridade": rd.uniform(0, 300),
            "Raio Molecular": rd.randint(0, 100),
        },
        "Grupos nitroso excluindo NO2": {
            "Número": Fragments.fr_nitroso(mol),
            "Massa Molecular": rd.uniform(0.5, 50),
            "Área de Superfície": rd.uniform(0.1, 5),
            "LogP": rd.random(),
            "Anéis Aromáticos": rd.randint(0, 5),
            "Número de Rotâmeros": rd.randint(0, 5),
            "Polaridade": rd.uniform(0, 300),
            "Raio Molecular": rd.randint(0, 100),
        },
        "Anéis de oxazol": {
            "Número": Fragments.fr_oxazole(mol),
            "Massa Molecular": rd.uniform(0.5, 50),
            "Área de Superfície": rd.uniform(0.1, 5),
            "LogP": rd.random(),
            "Anéis Aromáticos": rd.randint(0, 5),
            "Número de Rotâmeros": rd.randint(0, 5),
            "Polaridade": rd.uniform(0, 300),
            "Raio Molecular": rd.randint(0, 100),
        },
        "Grupos oxima": {
            "Número": Fragments.fr_oxime(mol),
            "Massa Molecular": rd.uniform(0.5, 50),
            "Área de Superfície": rd.uniform(0.1, 5),
            "LogP": rd.random(),
            "Anéis Aromáticos": rd.randint(0, 5),
            "Número de Rotâmeros": rd.randint(0, 5),
            "Polaridade": rd.uniform(0, 300),
            "Raio Molecular": rd.randint(0, 100),
        },
        "Locais de para-hidroxilação": {
            "Número": Fragments.fr_para_hydroxylation(mol),
            "Massa Molecular": rd.uniform(0.5, 50),
            "Área de Superfície": rd.uniform(0.1, 5),
            "LogP": rd.random(),
            "Anéis Aromáticos": rd.randint(0, 5),
            "Número de Rotâmeros": rd.randint(0, 5),
            "Polaridade": rd.uniform(0, 300),
            "Raio Molecular": rd.randint(0, 100),
        },
        "Fenóis": {
            "Número": Fragments.fr_phenol(mol),
            "Massa Molecular": rd.uniform(0.5, 50),
            "Área de Superfície": rd.uniform(0.1, 5),
            "LogP": rd.random(),
            "Anéis Aromáticos": rd.randint(0, 5),
            "Número de Rotâmeros": rd.randint(0, 5),
            "Polaridade": rd.uniform(0, 300),
            "Raio Molecular": rd.randint(0, 100),
        },
        "OH fenólico excluindo substituintes Hbond intramoleculares orto": {
            "Número": Fragments.fr_phenol_noOrthoHbond(mol),
            "Massa Molecular": rd.uniform(0.5, 50),
            "Área de Superfície": rd.uniform(0.1, 5),
            "LogP": rd.random(),
            "Anéis Aromáticos": rd.randint(0, 5),
            "Número de Rotâmeros": rd.randint(0, 5),
            "Polaridade": rd.uniform(0, 300),
            "Raio Molecular": rd.randint(0, 100),
        },
        "Grupos de ácido fosfórico": {
            "Número": Fragments.fr_phos_acid(mol),
            "Massa Molecular": rd.uniform(0.5, 50),
            "Área de Superfície": rd.uniform(0.1, 5),
            "LogP": rd.random(),
            "Anéis Aromáticos": rd.randint(0, 5),
            "Número de Rotâmeros": rd.randint(0, 5),
            "Polaridade": rd.uniform(0, 300),
            "Raio Molecular": rd.randint(0, 100),
        },
        "Grupos éster fosfórico": {
            "Número": Fragments.fr_phos_ester(mol),
            "Massa Molecular": rd.uniform(0.5, 50),
            "Área de Superfície": rd.uniform(0.1, 5),
            "LogP": rd.random(),
            "Anéis Aromáticos": rd.randint(0, 5),
            "Número de Rotâmeros": rd.randint(0, 5),
            "Polaridade": rd.uniform(0, 300),
            "Raio Molecular": rd.randint(0, 100),
        },
        "Anéis de piperdina": {
            "Número": Fragments.fr_piperdine(mol),
            "Massa Molecular": rd.uniform(0.5, 50),
            "Área de Superfície": rd.uniform(0.1, 5),
            "LogP": rd.random(),
            "Anéis Aromáticos": rd.randint(0, 5),
            "Número de Rotâmeros": rd.randint(0, 5),
            "Polaridade": rd.uniform(0, 300),
            "Raio Molecular": rd.randint(0, 100),
        },
        "Anéis de piperzina": {
            "Número": Fragments.fr_piperzine(mol),
            "Massa Molecular": rd.uniform(0.5, 50),
            "Área de Superfície": rd.uniform(0.1, 5),
            "LogP": rd.random(),
            "Anéis Aromáticos": rd.randint(0, 5),
            "Número de Rotâmeros": rd.randint(0, 5),
            "Polaridade": rd.uniform(0, 300),
            "Raio Molecular": rd.randint(0, 100),
        },
        "Amidas primárias": {
            "Número": Fragments.fr_priamide(mol),
            "Massa Molecular": rd.uniform(0.5, 50),
            "Área de Superfície": rd.uniform(0.1, 5),
            "LogP": rd.random(),
            "Anéis Aromáticos": rd.randint(0, 5),
            "Número de Rotâmeros": rd.randint(0, 5),
            "Polaridade": rd.uniform(0, 300),
            "Raio Molecular": rd.randint(0, 100),
        },
        "Sulfonamidas primárias": {
            "Número": Fragments.fr_prisulfonamd(mol),
            "Massa Molecular": rd.uniform(0.5, 50),
            "Área de Superfície": rd.uniform(0.1, 5),
            "LogP": rd.random(),
            "Anéis Aromáticos": rd.randint(0, 5),
            "Número de Rotâmeros": rd.randint(0, 5),
            "Polaridade": rd.uniform(0, 300),
            "Raio Molecular": rd.randint(0, 100),
        },
        "Anéis de piridina": {
            "Número": Fragments.fr_pyridine(mol),
            "Massa Molecular": rd.uniform(0.5, 50),
            "Área de Superfície": rd.uniform(0.1, 5),
            "LogP": rd.random(),
            "Anéis Aromáticos": rd.randint(0, 5),
            "Número de Rotâmeros": rd.randint(0, 5),
            "Polaridade": rd.uniform(0, 300),
            "Raio Molecular": rd.randint(0, 100),
        },
        "Nitrogênios quaternários": {
            "Número": Fragments.fr_quatN(mol),
            "Massa Molecular": rd.uniform(0.5, 50),
            "Área de Superfície": rd.uniform(0.1, 5),
            "LogP": rd.random(),
            "Anéis Aromáticos": rd.randint(0, 5),
            "Número de Rotâmeros": rd.randint(0, 5),
            "Polaridade": rd.uniform(0, 300),
            "Raio Molecular": rd.randint(0, 100),
        },
        "Sulfonamidas": {
            "Número": Fragments.fr_sulfonamd(mol),
            "Massa Molecular": rd.uniform(0.5, 50),
            "Área de Superfície": rd.uniform(0.1, 5),
            "LogP": rd.random(),
            "Anéis Aromáticos": rd.randint(0, 5),
            "Número de Rotâmeros": rd.randint(0, 5),
            "Polaridade": rd.uniform(0, 300),
            "Raio Molecular": rd.randint(0, 100),
        },
        "Grupos sulfona": {
            "Número": Fragments.fr_sulfone(mol),
            "Massa Molecular": rd.uniform(0.5, 50),
            "Área de Superfície": rd.uniform(0.1, 5),
            "LogP": rd.random(),
            "Anéis Aromáticos": rd.randint(0, 5),
            "Número de Rotâmeros": rd.randint(0, 5),
            "Polaridade": rd.uniform(0, 300),
            "Raio Molecular": rd.randint(0, 100),
        },
        "Acetilenos terminais": {
            "Número": Fragments.fr_term_acetylene(mol),
            "Massa Molecular": rd.uniform(0.5, 50),
            "Área de Superfície": rd.uniform(0.1, 5),
            "LogP": rd.random(),
            "Anéis Aromáticos": rd.randint(0, 5),
            "Número de Rotâmeros": rd.randint(0, 5),
            "Polaridade": rd.uniform(0, 300),
            "Raio Molecular": rd.randint(0, 100),
        },
        "Anéis de tetrazol": {
            "Número": Fragments.fr_tetrazole(mol),
            "Massa Molecular": rd.uniform(0.5, 50),
            "Área de Superfície": rd.uniform(0.1, 5),
            "LogP": rd.random(),
            "Anéis Aromáticos": rd.randint(0, 5),
            "Número de Rotâmeros": rd.randint(0, 5),
            "Polaridade": rd.uniform(0, 300),
            "Raio Molecular": rd.randint(0, 100),
        },
        "Anéis tiazólicos": {
            "Número": Fragments.fr_thiazole(mol),
            "Massa Molecular": rd.uniform(0.5, 50),
            "Área de Superfície": rd.uniform(0.1, 5),
            "LogP": rd.random(),
            "Anéis Aromáticos": rd.randint(0, 5),
            "Número de Rotâmeros": rd.randint(0, 5),
            "Polaridade": rd.uniform(0, 300),
            "Raio Molecular": rd.randint(0, 100),
        },
        "Tiocianatos": {
            "Número": Fragments.fr_thiocyan(mol),
            "Massa Molecular": rd.uniform(0.5, 50),
            "Área de Superfície": rd.uniform(0.1, 5),
            "LogP": rd.random(),
            "Anéis Aromáticos": rd.randint(0, 5),
            "Número de Rotâmeros": rd.randint(0, 5),
            "Polaridade": rd.uniform(0, 300),
            "Raio Molecular": rd.randint(0, 100),
        },
        "Anéis de tiofeno": {
            "Número": Fragments.fr_thiophene(mol),
            "Massa Molecular": rd.uniform(0.5, 50),
            "Área de Superfície": rd.uniform(0.1, 5),
            "LogP": rd.random(),
            "Anéis Aromáticos": rd.randint(0, 5),
            "Número de Rotâmeros": rd.randint(0, 5),
            "Polaridade": rd.uniform(0, 300),
            "Raio Molecular": rd.randint(0, 100),
        },
        "Alcanos não ramificados de pelo menos 4 membros (exclui alcanos halogenados)": {
            "Número": Fragments.fr_unbrch_alkane(mol),
            "Massa Molecular": rd.uniform(0.5, 50),
            "Área de Superfície": rd.uniform(0.1, 5),
            "LogP": rd.random(),
            "Anéis Aromáticos": rd.randint(0, 5),
            "Número de Rotâmeros": rd.randint(0, 5),
            "Polaridade": rd.uniform(0, 300),
            "Raio Molecular": rd.randint(0, 100),
        },
        "Grupos de ureia": {
            "Número": Fragments.fr_urea(mol),
            "Massa Molecular": rd.uniform(0.5, 50),
            "Área de Superfície": rd.uniform(0.1, 5),
            "LogP": rd.random(),
            "Anéis Aromáticos": rd.randint(0, 5),
            "Número de Rotâmeros": rd.randint(0, 5),
            "Polaridade": rd.uniform(0, 300),
            "Raio Molecular": rd.randint(0, 100),
        },
    }
    return grupos_funcionais
