grupos_funcionais = {
    'Hidroxila': '[OH]',
    'Amina Primária': '[NH2]',
    'Amina Secundária': '[NH1;!$(NC=O)]',
    'Amina Terciária': '[NH0;!$(NC=O)]',
    'Carbonila Aldeído': '[C;H1](=O)',
    'Carbonila Cetona': '[C;H2](=O)',
    'Carbonila Ácido Carboxílico': '[C;H1](=O)[OH]',
    'Carbonila Éster': '[C;H1](=O)[O;!$(OC=O)]',
    'Carbonila Amida': '[C;H1](=O)[NH2]',
    'Enol': '[C;H1]([OH])(=C)',
    'Epóxido': '[O]1[C;H1][C;H1]1',
    'Diazonio': '[N;H0]#[N]',
    'Nitrila': '[N]#[C]',
    'Alqueno': '[C;H2]=[C;H2]',
    'Alquino': '[C;H]#C',
    'Halogeneto de Acila': '[C;H1](=O)[Cl,Br,I]',
    'Halogeneto de Alquila': '[Cl,Br,I]',
    'Grupo Nitro': '[N+](=O)[O-]',
    'Grupo Nitrosa': '[N+]([O-])[OH]',
    'Sulfonato': '[S;X4](=O)(=O)[O-]',
    'Grupo Carbonato': '[C]([O;X1])=[O;X1]',
    'Grupo Isocianato': '[N;X2]=C=O',
    'Grupo Azida': '[N-]=[N+]=[N-]',
    'Grupo Cianato': 'N=C=O',
    'Grupo Nitroso': '[N+]([O-])=O',
    'Grupo Alquil Grignard': '[Mg]([Br,Cl,I])([C])',
    'Grupo Acetil': '[CH3](=O)',
    'Grupo Carboxamida': '[C;H1](=O)[NH2]',
    'Grupo Sulfonamida': '[S;X4](=O)(=O)[NH2]',
    'Grupo Isotiocianato': '[N;X2]=C=S',
    'Grupo Peróxido': '[O]O',
    'Grupo Halogeneto de Alquila': '[F,Cl,Br,I]',
    'Grupo Hidrazida': 'NN',
    'Grupo Nitroso Amida': '[N+]([O-])[NH2]',
    'Grupo Nitroso Éster': '[N+]([O-])[O;!$(OC=O)]',
    'Grupo Isonitrila': '[N;X2]=C#[C]',
    'Grupo Sulfonil Clorido': 'S(=O)(=O)Cl',
    'Grupo Tioéter': '[S;X2][C;H3]',
}